//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanwpf.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
        public string MaNCC { get; set; }
        public Nullable<double> Trigia { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
